/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abc: typeof import('./src/components/abc.vue')['default']
    AuthorCard: typeof import('./src/components/AuthorCard.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    VIcon: typeof import('./src/components/VIcon.vue')['default']
  }
}
